### ISSUE TITLE
Exclude particular apps from GTF

### ISSUE THREAD

**Issue by Borok93** [zalckos/GrandTheftFocus#1]
Hi, is there any way to exclude some apps from global GTF config?
Like it would be great if it worked for Telegram as I'm not comfortable when it comes foreground on every new message in personal chat.

Thanks!

**Comment by xalt7x** [comment]
You can disable such behaviour with a Telegram Desktop [option](https://github.com/telegramdesktop/tdesktop/issues/7885#issuecomment-628268069) (Settings > Notifications and Sounds > uncheck "Draw attention to the window").
