### ISSUE TITLE
Gnome 47 support?

### ISSUE THREAD

**Issue by DeN-AlB** [zalckos/GrandTheftFocus#12]
I just installed Gnome 47 in Arch (EndeavourOS) and the extension is not working anymore.

Are you working on an update for Gnome 47, already? 😉

**Comment by cedricroijakkers** [comment]
PS: The extension works fine if you add support for version 47 in `~/.local/share/gnome-shell/extensions/grand-theft-focus@zalckos.github.com/metadata.json`, it just needs a new release.

**Comment by DeN-AlB** [comment]
I didn't try and wanted to test it later. But thanks that you mention it. 👍

**Comment by DeN-AlB** [comment]
Works like a charm! Thanks a lot. :smile:

**Comment by zalckos** [comment]
Fixed. Extension on gnome.org waiting for review.
