### ISSUE TITLE
Improve focus transfer behavior

### ISSUE THREAD

**Issue by dblackCat** [zalckos/GrandTheftFocus#4]
Hi, thanks for this wonderful extension!

After long-term use, the idea of improvement appeared.

1. Now the window switches to the focus state immediately, regardless of whether the user initiated this action or the application.

A simple example:

I have two applications in the system:
1. Telegram
2. Whatsapp

For example, I work in some program. If a message arrives to the above messengers, their clients' windows immediately receive focus.

This is especially annoying during printing.

And the idea is the following. Determine whether the window is triggered by the user (a click event is possible). If the window is opened by the user focus the window.

In other cases, show the old notification - the window is ready, or do nothing.

I'm not sure if this can be implemented through an extension, but this functionality would be very useful.

**Comment by dblackCat** [comment]
If possible, I will try to make a screencast with the described behavior.

**Comment by dblackCat** [comment]
I'm sorry I didn't read this [https://github.com/zalckos/GrandTheftFocus/issues/1](https://github.com/zalckos/GrandTheftFocus/issues/1)

It solves the problem with Telegram, WhatsApp works without problems. 

It turns out there is no problem.

Only if you run steam. It launches the update window first, then the library window. He intercepts the focus, but not critically.

**Comment by harpreetstealth** [comment]
The issue is with Skype as well.
I use skype on different workspace, as soon as there is a message on skype,
Workspace is swicthed automatically.
